# 00. 컨텐츠 기반 추천시스템 - TF-IDF를 이용한 추천시스템 (기본예시)

In [1]:
docs = [
    '먹고 싶은 사과',  # 문서 0
    '먹고 싶은 바나나',  # 문서 1
    '길고 노란 바나나 바나나',
    '저는 과일이 좋아요'
]
docs

['먹고 싶은 사과', '먹고 싶은 바나나', '길고 노란 바나나 바나나', '저는 과일이 좋아요']

In [2]:
from sklearn.feature_extraction.text import CountVectorizer
vect = CountVectorizer() 

In [3]:
# 문장을 Counter Vectorizer 형태로 변환
countvect = vect.fit_transform(docs)
countvect # 4 x 9 : 4개의 문서에 9개의 단어

<4x9 sparse matrix of type '<class 'numpy.int64'>'
	with 12 stored elements in Compressed Sparse Row format>

In [4]:
# toarray()를 통해 문장이 vector 형태의 값을 얻을 수 있음.
# 하지만, 각 인덱스와 행렬이 무엇을 읨하는지는 알 수 없다.
countvect.toarray()

array([[0, 0, 0, 1, 0, 1, 1, 0, 0],
       [0, 0, 0, 1, 1, 0, 1, 0, 0],
       [0, 1, 1, 0, 2, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 1, 1]], dtype=int64)

In [5]:
vect.vocabulary_

{'먹고': 3,
 '싶은': 6,
 '사과': 5,
 '바나나': 4,
 '길고': 1,
 '노란': 2,
 '저는': 7,
 '과일이': 0,
 '좋아요': 8}

In [6]:
# sorted라는 함수를 통해서 단어를 정렬
sorted(vect.vocabulary_)

['과일이', '길고', '노란', '먹고', '바나나', '사과', '싶은', '저는', '좋아요']

In [7]:
import pandas as pd
countvect_df = pd.DataFrame(countvect.toarray(), columns = sorted(vect.vocabulary_))
countvect_df.index = ['문서1', '문서2', '문서3', '문서4']
countvect_df

과일이  길고  노란  먹고  바나나  사과  싶은  저는  좋아요
문서1    0   0   0   1    0   1   1   0    0
문서2    0   0   0   1    1   0   1   0    0
문서3    0   1   1   0    2   0   0   0    0
문서4    1   0   0   0    0   0   0   1    1

In [8]:
# 유사도 계산
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity(countvect_df, countvect_df)

array([[1.        , 0.66666667, 0.        , 0.        ],
       [0.66666667, 1.        , 0.47140452, 0.        ],
       [0.        , 0.47140452, 1.        , 0.        ],
       [0.        , 0.        , 0.        , 1.        ]])

1번 문서와 2번 문서가 유사, 2번 문서와 3번 문서가 유사

이번에는 TF-IDF를 사용

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer
vect = TfidfVectorizer()
tfvect = vect.fit(docs)
tfvect

TfidfVectorizer()

In [13]:
tfidf_df = pd.DataFrame(tfvect.transform(docs).toarray(), columns=sorted(vect.vocabulary_))
tfidf_df.index = ['문서1', '문서2', '문서3', '문서4']
tfidf_df

과일이       길고       노란        먹고      바나나        사과        싶은  \
문서1  0.00000  0.00000  0.00000  0.526405  0.00000  0.667679  0.526405   
문서2  0.00000  0.00000  0.00000  0.577350  0.57735  0.000000  0.577350   
문서3  0.00000  0.47212  0.47212  0.000000  0.74445  0.000000  0.000000   
문서4  0.57735  0.00000  0.00000  0.000000  0.00000  0.000000  0.000000   

          저는      좋아요  
문서1  0.00000  0.00000  
문서2  0.00000  0.00000  
문서3  0.00000  0.00000  
문서4  0.57735  0.57735

In [14]:
# 유사도 계산
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity(countvect_df, countvect_df)

array([[1.        , 0.66666667, 0.        , 0.        ],
       [0.66666667, 1.        , 0.47140452, 0.        ],
       [0.        , 0.47140452, 1.        , 0.        ],
       [0.        , 0.        , 0.        , 1.        ]])